// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNVWHsr0rgiOfJ3FpzEOPwnmkUEssX2A',
    appId: '1:244509611977:web:dc62799b42efa664eb7a18',
    messagingSenderId: '244509611977',
    projectId: 'reptitrack-app-637d8',
    authDomain: 'reptitrack-app-637d8.firebaseapp.com',
    storageBucket: 'reptitrack-app-637d8.firebasestorage.app',
    measurementId: 'G-4D1KKBB7TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi3IlZeZTtWLlmik9OII5NSYpN0RQxVB0',
    appId: '1:244509611977:android:a0e76a812fe9dc83eb7a18',
    messagingSenderId: '244509611977',
    projectId: 'reptitrack-app-637d8',
    storageBucket: 'reptitrack-app-637d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTBlB4eOA2gW-ZLBq4XwZ7LRItQNzZ8Wg',
    appId: '1:244509611977:ios:0a74e8d2b531be8ceb7a18',
    messagingSenderId: '244509611977',
    projectId: 'reptitrack-app-637d8',
    storageBucket: 'reptitrack-app-637d8.firebasestorage.app',
    iosBundleId: 'com.example.reptitrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTBlB4eOA2gW-ZLBq4XwZ7LRItQNzZ8Wg',
    appId: '1:244509611977:ios:0a74e8d2b531be8ceb7a18',
    messagingSenderId: '244509611977',
    projectId: 'reptitrack-app-637d8',
    storageBucket: 'reptitrack-app-637d8.firebasestorage.app',
    iosBundleId: 'com.example.reptitrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVNVWHsr0rgiOfJ3FpzEOPwnmkUEssX2A',
    appId: '1:244509611977:web:c17d6b32d36e9a76eb7a18',
    messagingSenderId: '244509611977',
    projectId: 'reptitrack-app-637d8',
    authDomain: 'reptitrack-app-637d8.firebaseapp.com',
    storageBucket: 'reptitrack-app-637d8.firebasestorage.app',
    measurementId: 'G-TJXDMKFBM1',
  );
}
